version: '3.9'

services:
  postgres:
    image: postgres:14.1-alpine
    expose:
      - '5432'
    ports:
      - '5432:5432'
    volumes:
      - hf-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - hf-network

  sak:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "uvicorn src.entrypoints.fastapi:app --host 0.0.0.0 --port 8000  --reload"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./.env
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    networks:
      - hf-network

volumes:
  hf-data:

networks:
  hf-network: